export interface BucketMetrics {
  label: string;
  trades: number;
  winRate: number;
  profitFactor: number;
  expectancy: number;
  netPnl: number;
  avgReturn: number;
}

export interface StockContribution {
  ticker: string;
  trades: number;
  netPnl: number;
  winRate: number;
  expectancy: number;
}

export interface ConcentrationReport {
  uniqueStocks: number;
  contributions: StockContribution[]; // sorted by netPnl descending
  top10: StockContribution[];
  /** % of TOTAL net P&L generated by the top 5 stocks. Can exceed 100% (or
   * be negative/undefined-feeling) when losers partly offset winners —
   * documented in TradeAnalytics.ts, not hidden. */
  top5PctOfTotalPnl: number;
  medianContribution: number;
  stocksWithPositiveExpectancy: number;
  stocksWithNegativeExpectancy: number;
}

export type EvidenceLevel = 'INSUFFICIENT_SAMPLE' | 'WEAK_EVIDENCE' | 'PROMISING' | 'STRONGER_EVIDENCE';

export interface EvidenceCriteria {
  numTrades: number;
  uniqueStocks: number;
  yearsCovered: number;
  regimesCovered: number;
  outOfSampleConsistent: boolean | null;
  parameterRobust: boolean | null;
}

export interface EvidenceAssessment {
  level: EvidenceLevel;
  reasons: string[];
  criteria: EvidenceCriteria;
}
