import { IntradayContext, latestIntradaySnapshot, todayIntradayCandle } from '@/types/intraday';
import { StrategyResult } from '@/types/strategy';
import { ScoreBreakdown, SignalClassification, SignalExplanation } from '@/types/scoring';
import { IntradayMarketContext } from './IntradayScoringEngine';

/**
 * Intraday counterpart to explainSignal (SignalExplainer.ts) — produces the
 * same SignalExplanation shape from an IntradayContext instead of a daily
 * StrategyContext, so OrderExecutor and every other consumer of
 * SignalExplanation work unchanged regardless of which pipeline produced
 * the signal. Every string here is generated by fixed logic from real
 * numbers, never by a model.
 */
export function explainIntradaySignal(
  context: IntradayContext,
  market: IntradayMarketContext,
  strategyResult: StrategyResult,
  scoreBreakdown: ScoreBreakdown,
  classification: SignalClassification
): SignalExplanation {
  const reasons: string[] = [...strategyResult.evidence];
  const risks: string[] = [...strategyResult.warnings];

  if (market.spy !== null) {
    const spySnap = latestIntradaySnapshot(market.spy);
    if (spySnap.vwap !== null && spySnap.close > spySnap.vwap) {
      reasons.push('SPY is trading above its session VWAP — a supportive broad-tape backdrop');
    } else if (spySnap.vwap !== null && spySnap.close < spySnap.vwap) {
      risks.push('SPY is trading below its session VWAP — a counter-tape setup');
    }
  }

  const snap = context.snapshots.length > 0 ? latestIntradaySnapshot(context) : null;
  if (snap?.rsi14 !== null && snap?.rsi14 !== undefined && snap.rsi14 > 80) {
    risks.push(`RSI at ${snap.rsi14.toFixed(1)} is extended`);
  }

  const invalidation =
    strategyResult.stop !== null
      ? `Price closes below $${strategyResult.stop.toFixed(2)}`
      : 'No valid stop level available — no active setup to invalidate';

  return {
    ticker: context.ticker,
    date: context.candles.length > 0 ? todayIntradayCandle(context).timestamp : new Date(0),
    strategy: strategyResult.strategy,
    classification,
    score: scoreBreakdown.total,
    scoreBreakdown,
    entry: strategyResult.entry,
    stop: strategyResult.stop,
    target: strategyResult.target,
    riskRewardRatio: strategyResult.riskRewardRatio,
    reasons,
    risks,
    invalidation,
  };
}
