import { StrategyContext, StrategyResult, latestSnapshot, todayCandle } from '@/types/strategy';
import { ScoreBreakdown, SignalClassification, SignalExplanation } from '@/types/scoring';

/**
 * Assembles a fully deterministic, evidence-based explanation from already-
 * computed data (the strategy's own evidence/warnings plus context-level
 * facts about regime/relative-strength/RSI). This is NOT the AI layer —
 * Phase 5 adds an LLM reasoning layer on top of this; every string produced
 * here is generated by fixed logic from real numbers, never by a model.
 */
export function explainSignal(
  context: StrategyContext,
  strategyResult: StrategyResult,
  scoreBreakdown: ScoreBreakdown,
  classification: SignalClassification
): SignalExplanation {
  const reasons: string[] = [...strategyResult.evidence];
  const risks: string[] = [...strategyResult.warnings];

  if (context.multiTimeframe.aligned) {
    reasons.push(
      `Weekly (${context.multiTimeframe.weeklyTrend}) and daily (${context.multiTimeframe.dailyTrend}) trends are aligned`
    );
  } else if (
    context.multiTimeframe.weeklyTrend !== 'neutral' &&
    context.multiTimeframe.dailyTrend !== 'neutral' &&
    context.multiTimeframe.weeklyTrend !== context.multiTimeframe.dailyTrend
  ) {
    risks.push(
      `Weekly (${context.multiTimeframe.weeklyTrend}) and daily (${context.multiTimeframe.dailyTrend}) trends conflict`
    );
  }

  if (context.marketRegime) {
    const label = context.marketRegime.label;
    if (label === 'strong_bullish' || label === 'bullish') {
      reasons.push(`Market regime is ${label.replace('_', ' ')}`);
    } else if (label === 'bearish' || label === 'strong_bearish') {
      risks.push(`Market regime is ${label.replace('_', ' ')} — this is a counter-regime setup`);
    } else if (label === 'high_volatility') {
      risks.push('Market regime shows elevated volatility across major indexes');
    }
  }

  if (context.relativeStrength) {
    if (context.relativeStrength.outperformingBoth) {
      reasons.push(
        `Outperforming both sector and benchmark over the trailing ${context.relativeStrength.periodDays} trading days`
      );
    } else if (context.relativeStrength.vsBenchmark < 0) {
      risks.push('Underperforming the broad-market benchmark over the relative-strength lookback period');
    }
  }

  const snap = context.snapshots.length > 0 ? latestSnapshot(context) : null;
  if (snap?.rsi14 !== null && snap?.rsi14 !== undefined && snap.rsi14 > 75) {
    risks.push(`RSI at ${snap.rsi14.toFixed(1)} is extended`);
  }
  if (snap?.historicalVolatility20 !== null && snap?.historicalVolatility20 !== undefined && snap.historicalVolatility20 > 0.6) {
    risks.push(`Historical volatility is elevated (${(snap.historicalVolatility20 * 100).toFixed(0)}% annualized)`);
  }

  const invalidation =
    strategyResult.stop !== null
      ? `Price closes below $${strategyResult.stop.toFixed(2)}`
      : 'No valid stop level available — no active setup to invalidate';

  return {
    ticker: context.ticker,
    date: context.candles.length > 0 ? todayCandle(context).timestamp : new Date(0),
    strategy: strategyResult.strategy,
    classification,
    score: scoreBreakdown.total,
    scoreBreakdown,
    entry: strategyResult.entry,
    stop: strategyResult.stop,
    target: strategyResult.target,
    riskRewardRatio: strategyResult.riskRewardRatio,
    reasons,
    risks,
    invalidation,
  };
}
