'use client';

import { Bot, Check, Info, ShieldAlert, Sparkles, TrendingDown, TrendingUp, Minus, X } from 'lucide-react';
import { Badge } from '@/components/ui/badge';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Skeleton } from '@/components/ui/skeleton';
import { ErrorState } from '@/components/common/StateMessage';
import { CLASS_TONE, REGIME_LABEL } from '@/components/ai/ScannerResults';
import { useTickerAnalysis } from '@/hooks/useScanner';
import { cleanAIText, formatDate, formatNumber, formatPercent, formatPrice, humanize } from '@/lib/utils/formatters';
import { cn } from '@/lib/utils/cn';
import type { TickerAnalysis, TimeframeTrend } from '@/lib/types';

/**
 * Computed trend bias from the scanner's multi-timeframe analysis. This is a
 * deterministic reading of moving-average structure, labelled as such — it is
 * not an LLM "sentiment" guess.
 */
function bias(a: TickerAnalysis): { label: string; tone: 'up' | 'down' | 'neutral'; Icon: typeof TrendingUp } {
  const { dailyTrend: d, weeklyTrend: w } = a.multiTimeframe;
  if (d === 'bullish' && w === 'bullish') return { label: 'Bullish', tone: 'up', Icon: TrendingUp };
  if (d === 'bearish' && w === 'bearish') return { label: 'Bearish', tone: 'down', Icon: TrendingDown };
  return { label: 'Neutral / mixed', tone: 'neutral', Icon: Minus };
}

const trendText = (t: TimeframeTrend) => t.charAt(0).toUpperCase() + t.slice(1);

function Row({ label, children, hint }: { label: string; children: React.ReactNode; hint?: string }) {
  return (
    <div className="flex items-baseline justify-between gap-3 py-1" title={hint}>
      <dt className="text-xs text-muted">{label}</dt>
      <dd className="num text-right text-sm">{children}</dd>
    </div>
  );
}

function List({ items, icon, tone }: { items: string[]; icon: React.ReactNode; tone: string }) {
  if (items.length === 0) return null;
  return (
    <ul className="space-y-1.5">
      {items.map((t, i) => (
        <li key={i} className="flex gap-2 text-xs leading-relaxed">
          <span className={cn('mt-0.5 shrink-0', tone)}>{icon}</span>
          <span>{cleanAIText(t)}</span>
        </li>
      ))}
    </ul>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div className="border-t border-border pt-3">
      <h3 className="mb-2 text-[11px] font-semibold uppercase tracking-wider text-faint">{title}</h3>
      {children}
    </div>
  );
}

export function AIInsights({ symbol }: { symbol: string }) {
  const { data, error, isLoading } = useTickerAnalysis(symbol);

  return (
    <Card className="flex h-full min-h-0 flex-col">
      <CardHeader>
        <CardTitle className="flex items-center gap-1.5">
          <Sparkles className="size-3.5 text-accent" /> AI Insights · <span className="num normal-case text-text">{symbol}</span>
        </CardTitle>
        {data?.ai && (
          <Badge tone={data.ai.source === 'ai' ? 'accent' : 'neutral'} title={data.ai.status === 'fallback' ? data.ai.reason : 'Explanation generated by Claude from computed data only'}>
            <Bot className="size-3" /> {data.ai.source === 'ai' ? 'Claude' : 'Rule-based fallback'}
          </Badge>
        )}
      </CardHeader>
      <CardContent className="scroll-thin min-h-0 flex-1 space-y-3 overflow-y-auto">
        {isLoading && (
          <div className="space-y-3" aria-busy>
            <p className="text-xs text-muted">Running the scanner and asking the AI layer to explain it… (can take ~20s)</p>
            <Skeleton className="h-16 w-full" />
            <Skeleton className="h-4 w-3/4" />
            <Skeleton className="h-4 w-2/3" />
            <Skeleton className="h-24 w-full" />
          </div>
        )}
        {error && !isLoading && <ErrorState error={error} what="AI analysis" />}
        {data && !isLoading && <Analysis a={data} />}
      </CardContent>
    </Card>
  );
}

function Analysis({ a }: { a: TickerAnalysis }) {
  const top = a.signals[0];
  const b = bias(a);
  const ai = a.ai?.result;
  const hist = top?.historical;

  return (
    <>
      {/* Headline: classification + computed bias */}
      <div className="grid grid-cols-2 gap-2">
        <div className="rounded-lg bg-panel-2 p-3">
          <p className="text-[11px] uppercase tracking-wider text-faint">Scanner call</p>
          <div className="mt-1 flex items-center gap-2">
            <Badge tone={CLASS_TONE[top.classification]} className="text-xs">{top.classification}</Badge>
            <span className="num text-sm text-muted">{top.score.toFixed(0)}/100</span>
          </div>
          <p className="mt-1 truncate text-[11px] text-muted">{humanize(top.strategy)}</p>
        </div>
        <div className="rounded-lg bg-panel-2 p-3" title="Computed from daily and weekly moving-average structure — deterministic, not an AI guess">
          <p className="text-[11px] uppercase tracking-wider text-faint">Trend bias</p>
          <p className={cn('mt-1 flex items-center gap-1.5 text-sm font-semibold', b.tone === 'up' && 'text-up', b.tone === 'down' && 'text-down')}>
            <b.Icon className="size-4" /> {b.label}
          </p>
          <p className="mt-1 text-[11px] text-muted">D {trendText(a.multiTimeframe.dailyTrend)} · W {trendText(a.multiTimeframe.weeklyTrend)}</p>
        </div>
      </div>

      {ai && <p className="text-sm leading-relaxed">{cleanAIText(ai.summary)}</p>}

      <Section title="Trade plan (from scanner rules)">
        {top.setupDetected ? (
          <dl>
            <Row label="Entry">{formatPrice(top.entry)}</Row>
            <Row label="Stop">{<span className="text-down">{formatPrice(top.stop)}</span>}</Row>
            <Row label="Target">{<span className="text-up">{formatPrice(top.target)}</span>}</Row>
            <Row label="Risk / reward">{formatNumber(top.riskRewardRatio)}</Row>
          </dl>
        ) : (
          <p className="text-xs leading-relaxed text-muted">No strategy triggered on the last close, so there’s no entry/stop/target. {top.invalidation}</p>
        )}
      </Section>

      <Section title="Key levels (computed)">
        <dl>
          <Row label="Resistance · 20d / 60d">{formatPrice(a.levels.resistance20)} / {formatPrice(a.levels.resistance60)}</Row>
          <Row label="Support · 20d / 60d">{formatPrice(a.levels.support20)} / {formatPrice(a.levels.support60)}</Row>
          <Row label="Last swing high / low">{formatPrice(a.levels.lastSwingHigh)} / {formatPrice(a.levels.lastSwingLow)}</Row>
          <Row label="RSI 14 · ADX 14">{formatNumber(a.indicators.rsi14, 1)} · {formatNumber(a.indicators.adx14, 1)}</Row>
          <Row label="ATR 14" hint="Average true range — typical daily move in $">{formatPrice(a.indicators.atr14)}</Row>
          {a.relativeStrength && (
            <Row label={`Return vs SPY · ${a.relativeStrength.periodDays}d`}>
              {formatPercent(a.relativeStrength.stockReturn * 100, 1)}
              {a.relativeStrength.vsBenchmark !== undefined && <span className="text-muted"> ({formatPercent(a.relativeStrength.vsBenchmark * 100, 1)} rel)</span>}
            </Row>
          )}
          {a.marketRegime && <Row label="Market regime">{REGIME_LABEL[a.marketRegime.label]}</Row>}
        </dl>
      </Section>

      {ai ? (
        <>
          {(ai.supportingEvidence.length > 0 || ai.conflictingEvidence.length > 0) && (
            <Section title="Evidence">
              <div className="space-y-2">
                <List items={ai.supportingEvidence} icon={<Check className="size-3.5" />} tone="text-up" />
                <List items={ai.conflictingEvidence} icon={<X className="size-3.5" />} tone="text-down" />
              </div>
            </Section>
          )}
          {ai.riskFlags.length > 0 && (
            <Section title="Risk flags">
              <List items={ai.riskFlags} icon={<ShieldAlert className="size-3.5" />} tone="text-warn" />
            </Section>
          )}
        </>
      ) : (
        <Section title="Rule evidence">
          <div className="space-y-2">
            <List items={top.reasons} icon={<Check className="size-3.5" />} tone="text-up" />
            <List items={top.risks} icon={<ShieldAlert className="size-3.5" />} tone="text-warn" />
          </div>
        </Section>
      )}

      {hist?.baseline && (
        <Section title="Historical context (in-sample backtest)">
          <dl>
            <Row label="Trades · profit factor">{hist.baseline.trades} · {formatNumber(hist.baseline.profitFactor)}</Row>
            {hist.regime && (
              <Row label={`Win rate in ${REGIME_LABEL[hist.regime.label.split(' / ')[1]] ?? 'regime'}`} hint={hist.regime.note ?? undefined}>
                {hist.regime.winRatePct !== null ? `${hist.regime.winRatePct.toFixed(1)}%` : '—'} <span className="text-muted">({hist.regime.trades} trades{hist.regime.sampleSizeSufficient ? '' : ', too few'})</span>
              </Row>
            )}
          </dl>
          <p className="mt-2 text-[11px] leading-relaxed text-faint">{hist.baseline.concentrationNote}</p>
        </Section>
      )}

      <div className="flex gap-2 rounded-lg border border-border p-3 text-[11px] leading-relaxed text-muted">
        <Info className="mt-0.5 size-3.5 shrink-0" />
        <p>
          Daily-bar analysis as of {formatDate(a.asOf)}. No win probability or 24–48h forecast is shown, because the scanner doesn’t produce a calibrated one — the AI layer only explains computed values and never adds its own numbers.
          {ai?.limitations[0] ? ` ${cleanAIText(ai.limitations[0])}` : ''}
        </p>
      </div>
    </>
  );
}
